### ISSUE TITLE
Deploy German translation

### ISSUE THREAD

**Issue by paul2keller** [rightsstatements/rightsstatements.github.io#131]
deploy the German translation, based on the final approved translation document. This concerns both the statements and the parts of the website texts. Please refer to the approved german translation document for the texts:

[180525RS_1.0_translation_DE_approved.pdf](https://github.com/rightsstatements/rightsstatements.github.io/files/2039547/180525RS_1.0_translation_DE_approved.pdf)

**Comment by anarchivist** [comment]
@aisaac I've reflected the expected changes in the changes, rather than using what was in the document verbatim.

@paul2keller The last page of the translation document does not have translations for the following:

* `This statement is provided by <a href=“http://rightsstatements.org”>rightsstatements.org</a>`
* `URI for this statement:`

Otherwise, the linked pull requests implement the German translations and are awaiting merging and review. As noted in Slack, I discovered a few blocking issues while testing the changes: rightsstatements/rights-app#65 and rightsstatements/rights-app#66; @literarymachine will look into it but has limited time over the next week or two.

**Comment by paul2keller** [comment]
@anarchivist i have asked the  german translation team to provide the missing translation. @aisaac "RechtehinweisE" is indeed a typo and should be changed to "Rechtehinweise". on the other hand i am not seeing any problem with translating

> To license your own Work, use a License offered at http://creativecommons.org

with 

> Um ein eigenes Werk zu lizenzieren, nutzen Sie bitte eine unter http://creativecommons.org/ angebotene Lizenz. 

other than that there is no "." at the end of the english language version. was that what you are trying to point out.

**Comment by aisaac** [comment]
@paul2keller I didn't see any blocking point for the translation indeed (@anarchivist had fixed it in the data anyway), just flagging in case this would have repercussions for later.
For the link to CC, the point is that in the translation table the English version has the markup visible, while the German version just 'embeds' the hyperlink. We can fix it ourselves when we see it. I just have no idea of what another reader could infer from this formatting difference, but as it's there I'm flagging it.

**Comment by paul2keller** [comment]
i have uploaded a new version of the DE translation document to rightsstatements.github.io/files/180531RS_1.0_translation_DE_approved.pdf This version fixes the syntax of the links and adds the two missing translations at the end.
