### ISSUE TITLE
language selection does not carry on to the declarations

### ISSUE THREAD

**Issue by puik** [rightsstatements/rightsstatements.github.io#138]
When viewing the [RS site in German](http://rightsstatements.org/de/) and clicking the **statements** there is an intermediary view displayed and then the [**declarations page is opened in English**](http://rightsstatements.org/page/1.0/?language=en).
See screenshots below:

![screen shot 2018-06-05 at 10 16 47](https://user-images.githubusercontent.com/2512379/40961005-036aa798-68aa-11e8-8482-c4446e6176b9.png)
![screen shot 2018-06-05 at 10 16 49](https://user-images.githubusercontent.com/2512379/40961050-1fd66aca-68aa-11e8-83b1-ed539027e8b9.png)
![screen shot 2018-06-05 at 10 16 52](https://user-images.githubusercontent.com/2512379/40961054-21ff72d8-68aa-11e8-8b7b-6709d86af19c.png)

**Comment by paul2keller** [comment]
the intermediary view is also present when navigating from the EN version of the home page. as regards to the fact that the statements page is displayed in EN when clicking through this is expected (but not necessarily ideal behaviour) as we are currently basing the display language on the preferred language of the the browser. Again we will discuss these issues later this week an come back to them here

**Comment by anarchivist** [comment]
@paul2keller has it correct; this is implemented using [content negotiation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation). If the priority order for languages in your browser has German set above English, you should see the German pages for the statements by default.

![img](https://user-images.githubusercontent.com/73732/40987686-13fe27d0-689e-11e8-9f0d-31b6745abdd2.gif)

**Comment by puik** [comment]
I do not agree with the argumentation – I find it is **really bad UX when language selection does not carry on from page to page**, for me the site seems broken like that and I can't promote the Estonian translation live until it behaves like that. 

I have my browser settings on English only and I do believe this is also the case with many Estonian users. When I have arrived on the [first page in Estonian](http://rightsstatements.org/et/) and click **declarations** I wish to continue in Estonian and I do not expect the fallback to English because of my browser settings. We can't expect ordinary users to go to the url to change language=en to language=et on the url.

The same problem continues when I want to open the full description of any declarations...

**Comment by aisaac** [comment]
Hi first we need a precise caracterization of what's wanted.

 From @puik 's comment I understand that the first need is about changing the link at the top of the page http://rightsstatements.org/et/,  to make sure that we reach https://rightsstatements.org/page/1.0/?language=et whatever be the language preference in the browser.
This could be either by fixing the behaviour for the current link (http://rightsstatements.org/et/statements/) or by changing it to https://rightsstatements.org/page/1.0/?language=et directly. The latter would be much harder to maintain on the long run, but anyway, either should be doable.

My main worry is that we would spend time on this to realize @puik is still not happy. What should happen on the next page indeed? https://rightsstatements.org/page/1.0/?language=et is full of statement URIs that MUST not be changed.
This is also true for individual statements pages like http://rightsstatements.org/page/CNE/1.0/?language=et. We can't change http://rightsstatements.org/vocab/CNE/1.0/ there.
So users will still have the possibility to click on URIs that will lead them to pages in non-Estonian languages if their browsers is not set to request pages in Estonian.

**Comment by puik** [comment]
Well definitely all the aspects of multilinguality have to be thought through and optimal solutions implemented.

**My main concern at the moment is how can a user browse through the page and declarations in another language than English without fallback to English and changing the language parameter in the URL**. After implementation on repositories most visits might be to individual statements pages but at the moment for popularisation, awareness-raising and outreach the site has to be navigatable in a single language.

For me one of the easiest solutions still seems adding these *available in ...* text links to the pages (#139). So even when the fallback occurs user could easily change back.

But I also think that the language selection should carry on. On [**statements page in Estonian**](http://rightsstatements.org/page/1.0/?language=et) of course the listed URIs shouldn't be changed, but when clicking any of these the Estonian language parameter could be added to the end of the url? On **Creative Commons** it has been solved.

**Comment by aisaac** [comment]
@puik you mean that on
http://rightsstatements.org/page/1.0/?language=et
it should be possible to click on
http://rightsstatements.org/vocab/InC/1.0/
and be automatically redirected to
http://rightsstatements.org/page/InC/1.0/?language=et
even when one's browser is set to request English?

On which page do you see this in CC? I'm curious, let's have a look at this design.

**Comment by puik** [comment]
> @puik you mean that on http://rightsstatements.org/page/1.0/?language=et it should be possible to click on http://rightsstatements.org/vocab/InC/1.0/ and be automatically redirected to http://rightsstatements.org/page/InC/1.0/?language=et even when one's browser is set to request English?

Yes, this is what I meant.
Otherwise the only option to read the statements in Estonian would be to change the url which is not something obvious for ordinary museum staff.

> On which page do you see this in CC? I'm curious, let's have a look at this design.

Indeed, maybe not all the flow I'd like to have on RS is present on CC but at least when on a [licence summary page in French](https://creativecommons.org/licenses/by/4.0/deed.fr) then clicking to the **full licence** takes one to the [licence page in French](https://creativecommons.org/licenses/by/4.0/legalcode.fr).

There is a prominent note on the page about *Les traductions officielles de la présente licence sont disponibles en d'autres langues* taking the user to the page footer where all the other available translations are listed.

Also from the [*resumé* page](https://creativecommons.org/licenses/by/4.0/deed.fr) the link to [*utiliser la licence* opens a page in French](https://creativecommons.org/choose/results-one?license_code=by&amp;jurisdiction=&amp;version=4.0&amp;lang=fr).

**Comment by literarymachine** [comment]
> @puik you mean that on http://rightsstatements.org/page/1.0/?language=et it should be possible to click on http://rightsstatements.org/vocab/InC/1.0/ and be automatically redirected to http://rightsstatements.org/page/InC/1.0/?language=et even when one's browser is set to request English?

We could think about linking directly to the `page` in the current language from the logo and the title of the statement, see #145. The `URI` link could continue to link to the abstract `vocab` URI.

**Comment by puik** [comment]
> We could think about linking directly to the page in the current language from the logo and the title of the statement, see #145. The URI link could continue to link to the abstract vocab URI.

Yes, why not like that!

**Comment by aisaac** [comment]
Thanks for the explanations, and the opening of #145.
(NB: I've also opened #146 because I think this is really a basic UI issue that should be fixed independently on what we think about content negotiation for languages.)

My problem is the example of https://creativecommons.org/licenses/by/4.0/legalcode.fr is a bit of a counter-example for me. I mean, it works well, and in the CC context is good. But I can clearly see why in a machine readable environment it leads to Europeana and its partners having to waste an awful lot of time explaining to data providers than what they have to provide in the actual metadata is https://creativecommons.org/licenses/by/4.0/ *not* https://creativecommons.org/licenses/by/4.0/legalcode.fr.

This said this concern of mine would be somehow alleviated if you are still happy with having the 'abstract' URI still highly prominent in the statement page and we could find a work-around to go from a statement page in English (possibly reached from the Estonian vocabulary page).

But I need to double check with you though: is a user path
1. http://rightsstatements.org/page/1.0/?language=et
->
2. http://rightsstatements.org/page/InC/1.0/?language=en
->
3. http://rightsstatements.org/page/InC/1.0/?language=et
ok, if the link between 2 and 3 is relatively easy to find for the user, and both 2 and 3 still *prominently* feature the abstract URI?

If yes, then maybe having a solution like the footer of https://creativecommons.org/licenses/by/4.0/legalcode.fr (with links to all languages for an individual statement page) is the best option.
At least it can be defended even if one believes that the real way to get to a language-specific page is to use browser preferences and content negotiation.
And I believe it's possible without too much effort. This said this is out of my area of expertise, and I'm already using too much time on discussing this (as Paul said, we're a small consortium with little time and resources on our hands).

As for using the trick of adding language-specific links on the icons and the title, I'm not sure it will provide a great UX, as these elements do not bring a "language-specific call to action" that's visually obvious.

**Comment by literarymachine** [comment]
> As for using the trick of adding language-specific links on the icons and the title, I'm not sure it will provide a great UX, as these elements do not bring a "language-specific call to action" that's visually obvious.

The title is in a specific language, so I would argue that one would expect to not change the language when clicking on it.

**Comment by aisaac** [comment]
You're right @literarymachine . But it's not what a UX designer would call a strong call to action, especially when there's the big 'abstract' URI just below.

**Comment by puik** [comment]
> ... it leads to Europeana and its partners having to waste an awful lot of time explaining to data providers than what they have to provide in the actual metadata is https://creativecommons.org/licenses/by/4.0/ *not* https://creativecommons.org/licenses/by/4.0/legalcode.fr.

Can this really be such a problem? The language-specific end of the url can be stripped? It should be even easier with RS as there the language is a parameter after **?**, so the regex is even simpler.

> This said this concern of mine would be somehow alleviated if you are still happy with having the 'abstract' URI still highly prominent in the statement page and we could find a work-around to go from a statement page in English (possibly reached from the Estonian vocabulary page).

I have nothing against the abstract 'naked' URI, especially when the logotypes and titles would be clickable and leading to language-specific statement as @literarymachine also suggested.

> But I need to double check with you though: is a user path
1. http://rightsstatements.org/page/1.0/?language=et ->
2. http://rightsstatements.org/page/InC/1.0/?language=en ->
3. http://rightsstatements.org/page/InC/1.0/?language=et
ok, if the link between 2 and 3 is relatively easy to find for the user, and both 2 and 3 still *prominently* feature the abstract URI?

I think so.

> If yes, then maybe having a solution like the footer of https://creativecommons.org/licenses/by/4.0/legalcode.fr (with links to all languages for an individual statement page) is the best option.

Yep

**Comment by aisaac** [comment]
@puik ok it seems that we can have a way forward about the design then. *If* we have the time to work on something...

For the record yes it's a big problem if a metadata 'expert' starts to right-click and paste and use http://rightsstatements.org/page/InC/1.0/?language=et in their metadata instead of the 'abstract' URI. I've seen this happens since ten years I'm in this business... And then basically the metadata is wrong and much less interoperable, which defeats the original purpose of rightsstatements.org.

As for 'stripping' and other post
Stripping the URI is doable for implementing (say) Europeana's portal on top of imperfect metadata values, but one cannot expect all of Europeana's data re-users to implement this stripping on their own. Besides, if one allows value because stripping is possible, then why wouldn't one rely on some process to accept also "InC", "In Copyright" and every possible fancy re-writing that is understandable for a human but quite opaque for a machine? Once the door is open for imperfect values, then pretty much anything goes. And eventually it is up to our colleagues at Europeana or Europeana's data partners to spend time fixing the issues... This is quite a high price to pay.
