### ISSUE TITLE
available in ... list

### ISSUE THREAD

**Issue by puik** [rightsstatements/rightsstatements.github.io#139]
The declarations page should have after the introduction a clearly brought out language selection (*Declarations available in **German**, **Estonian**.*) as on Creative Commons pages.

This **also available in ...** should be also on every page of individual declarations.

The question is could it be used separately from the site's language selection... For instance having the site in English but looking at declarations only in another language.

![screen shot 2018-06-05 at 10 16 52 2](https://user-images.githubusercontent.com/2512379/40961831-68142b36-68ac-11e8-84ae-d67690fa09da.png)

**Comment by paul2keller** [comment]
thanks @puik this is an ongoing internal discussion how e can best handle the language switching and the ineveitable incompleteness of the translation of the site texts. we have this on the agenda for a meeting later this week and will then get back to this issue

**Comment by aisaac** [comment]
@paul2keller can you answer with the resolution that we made in the Steering Committee meeting?

**Comment by paul2keller** [comment]
@puik so we have discussed this at the SC meeting on friday and have come to the conclusion that for now we will  maintain a minimalist approach here. This means that we are not offering an explicit language switcher on the site and continue to rely on content negotiation based on proffered browser language. (there is of course a navigation path from the english version of the homepage > translations overview page to the translated versions). 

We have also decided to only translate the homepage, the statements overview page and the statements and to direct visitors to the english language version of the site for anything else. This is mainly due to keeping translation manageable as we get more and more of them.

**Comment by paul2keller** [comment]
so the above scenario that you give is not necessarily correct. if a user clicks on a link to a statement on a foreign repository, the statement will not necessarily be displayed in english, but in the the preferred language of the users browser. So i do not see the need to change this behaviour here.

**Comment by puik** [comment]
Yes, I agree, but still I find it not reasonable that the flow is so much dependent on the user's browser's settings.
Why not show the user in a clear manner in which languages is the declaration available (as on CC licence information pages)?

**Comment by paul2keller** [comment]
so the answer to your question is that we try to avoid all unnecessary complexity. We currently have very limited ressources and in that situation it seems unwise to add new functionality. `We may want to revise this decision at a later stage when we also have a more information on how translations are used / perform.
